// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quotient.proto

package de.evoila.cf.autoscaler.kafka.protobuf;

public final class PbQuotient {
  private PbQuotient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoQuotientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autoscaler.ProtoQuotient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>string appId = 2;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string appId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>int32 requests = 3;</code>
     */
    int getRequests();

    /**
     * <code>int32 instances = 5;</code>
     */
    int getInstances();

    /**
     * <code>int32 quotient = 6;</code>
     */
    int getQuotient();

    /**
     * <code>string description = 7;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 7;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code autoscaler.ProtoQuotient}
   */
  public  static final class ProtoQuotient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:autoscaler.ProtoQuotient)
      ProtoQuotientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoQuotient.newBuilder() to construct.
    private ProtoQuotient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoQuotient() {
      timestamp_ = 0L;
      appId_ = "";
      requests_ = 0;
      instances_ = 0;
      quotient_ = 0;
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoQuotient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 24: {

              requests_ = input.readInt32();
              break;
            }
            case 40: {

              instances_ = input.readInt32();
              break;
            }
            case 48: {

              quotient_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.internal_static_autoscaler_ProtoQuotient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.internal_static_autoscaler_ProtoQuotient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.class, de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object appId_;
    /**
     * <code>string appId = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string appId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTS_FIELD_NUMBER = 3;
    private int requests_;
    /**
     * <code>int32 requests = 3;</code>
     */
    public int getRequests() {
      return requests_;
    }

    public static final int INSTANCES_FIELD_NUMBER = 5;
    private int instances_;
    /**
     * <code>int32 instances = 5;</code>
     */
    public int getInstances() {
      return instances_;
    }

    public static final int QUOTIENT_FIELD_NUMBER = 6;
    private int quotient_;
    /**
     * <code>int32 quotient = 6;</code>
     */
    public int getQuotient() {
      return quotient_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 7;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
      }
      if (requests_ != 0) {
        output.writeInt32(3, requests_);
      }
      if (instances_ != 0) {
        output.writeInt32(5, instances_);
      }
      if (quotient_ != 0) {
        output.writeInt32(6, quotient_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
      }
      if (requests_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, requests_);
      }
      if (instances_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, instances_);
      }
      if (quotient_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, quotient_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient)) {
        return super.equals(obj);
      }
      de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient other = (de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && (getRequests()
          == other.getRequests());
      result = result && (getInstances()
          == other.getInstances());
      result = result && (getQuotient()
          == other.getQuotient());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
      hash = (53 * hash) + getRequests();
      hash = (37 * hash) + INSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getInstances();
      hash = (37 * hash) + QUOTIENT_FIELD_NUMBER;
      hash = (53 * hash) + getQuotient();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code autoscaler.ProtoQuotient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:autoscaler.ProtoQuotient)
        de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.internal_static_autoscaler_ProtoQuotient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.internal_static_autoscaler_ProtoQuotient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.class, de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.Builder.class);
      }

      // Construct using de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        appId_ = "";

        requests_ = 0;

        instances_ = 0;

        quotient_ = 0;

        description_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.internal_static_autoscaler_ProtoQuotient_descriptor;
      }

      @java.lang.Override
      public de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient getDefaultInstanceForType() {
        return de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.getDefaultInstance();
      }

      @java.lang.Override
      public de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient build() {
        de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient buildPartial() {
        de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient result = new de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient(this);
        result.timestamp_ = timestamp_;
        result.appId_ = appId_;
        result.requests_ = requests_;
        result.instances_ = instances_;
        result.quotient_ = quotient_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient) {
          return mergeFrom((de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient other) {
        if (other == de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (other.getRequests() != 0) {
          setRequests(other.getRequests());
        }
        if (other.getInstances() != 0) {
          setInstances(other.getInstances());
        }
        if (other.getQuotient() != 0) {
          setQuotient(other.getQuotient());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string appId = 2;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private int requests_ ;
      /**
       * <code>int32 requests = 3;</code>
       */
      public int getRequests() {
        return requests_;
      }
      /**
       * <code>int32 requests = 3;</code>
       */
      public Builder setRequests(int value) {
        
        requests_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requests = 3;</code>
       */
      public Builder clearRequests() {
        
        requests_ = 0;
        onChanged();
        return this;
      }

      private int instances_ ;
      /**
       * <code>int32 instances = 5;</code>
       */
      public int getInstances() {
        return instances_;
      }
      /**
       * <code>int32 instances = 5;</code>
       */
      public Builder setInstances(int value) {
        
        instances_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 instances = 5;</code>
       */
      public Builder clearInstances() {
        
        instances_ = 0;
        onChanged();
        return this;
      }

      private int quotient_ ;
      /**
       * <code>int32 quotient = 6;</code>
       */
      public int getQuotient() {
        return quotient_;
      }
      /**
       * <code>int32 quotient = 6;</code>
       */
      public Builder setQuotient(int value) {
        
        quotient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quotient = 6;</code>
       */
      public Builder clearQuotient() {
        
        quotient_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 7;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 7;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 7;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:autoscaler.ProtoQuotient)
    }

    // @@protoc_insertion_point(class_scope:autoscaler.ProtoQuotient)
    private static final de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient();
    }

    public static de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoQuotient>
        PARSER = new com.google.protobuf.AbstractParser<ProtoQuotient>() {
      @java.lang.Override
      public ProtoQuotient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoQuotient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoQuotient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoQuotient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.evoila.cf.autoscaler.kafka.protobuf.PbQuotient.ProtoQuotient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autoscaler_ProtoQuotient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autoscaler_ProtoQuotient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Quotient.proto\022\nautoscaler\"}\n\rProtoQuo" +
      "tient\022\021\n\ttimestamp\030\001 \001(\003\022\r\n\005appId\030\002 \001(\t\022" +
      "\020\n\010requests\030\003 \001(\005\022\021\n\tinstances\030\005 \001(\005\022\020\n\010" +
      "quotient\030\006 \001(\005\022\023\n\013description\030\007 \001(\tBR\n&d" +
      "e.evoila.cf.autoscaler.kafka.protobufB\nP" +
      "bQuotient\252\002\033de.cf.autoscaler.PbQuotientb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_autoscaler_ProtoQuotient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autoscaler_ProtoQuotient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autoscaler_ProtoQuotient_descriptor,
        new java.lang.String[] { "Timestamp", "AppId", "Requests", "Instances", "Quotient", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
